include: package:all_lint_rules_community/all.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "lib/gen/**"
  errors:
    # Without ignore here, we cause import of all_lint_rules to warn, because some rules conflict.
    # We explicitly enabled even conflicting rules and are fixing the conflicts in this file.
    included_file_warning: ignore
    todo: info
    unused_element: ignore

linter:
  rules:
    prefer_double_quotes: false
    prefer_relative_imports: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    prefer_final_parameters: false
    unnecessary_final: false
    always_specify_types: false
    prefer_expression_function_bodies: false
    diagnostic_describe_all_properties: false
    cascade_invocations: false
    prefer_int_literals: false
    one_member_abstracts: false
    comment_references: false
    omit_local_variable_types: false
    avoid_catches_without_on_clauses: false
    require_trailing_commas: false
