name: punycode_converter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  bloc: ^8.0.3
  copy_with_extension: ^4.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  fpdart: ^0.2.0
  keyboard_dismisser: ^3.0.0
  punycode: ^1.0.0
  toor: ^1.0.0

dev_dependencies:
  all_lint_rules_community: ^0.0.12
  build_runner: ^2.2.0
  copy_with_extension_gen: ^4.0.2
  flutter_test:
    sdk: flutter
  intl_utils: ^2.7.0

dependency_overrides:
  meta: 1.7.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Localization
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen
