name: punycode_converter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  basic_utils: ^4.4.2
  bloc: ^8.0.3
  copy_with_extension: ^4.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  fpdart: ^0.2.0
  in_app_review: ^2.0.4
  keyboard_dismisser: ^3.0.0
  modal_bottom_sheet: ^2.1.0
  toor: ^1.0.0
  url_launcher: ^6.1.5

dev_dependencies:
  all_lint_rules_community: ^0.0.12
  build_runner: ^2.2.0
  change_app_package_name: ^1.1.0
  copy_with_extension_gen: ^4.0.2
  flutter_oss_licenses: ^2.0.1
  flutter_test:
    sdk: flutter
  intl_utils: ^2.7.0

dependency_overrides:
  meta: 1.7.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: Localization
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen
